name: Treadful
version: ${project.version}
main: com.craftmend.treadful.Treadful
description: A plugin that fixes Minecraft's horrible performance by injecting and replacing native server code with multithreaded logic.
author: Mindgamesnl